FROM armdocker.rnd.ericsson.se/proj_oss_releases/enm/jboss-dps:latest

COPY createSymlinks.sh /src/test/resources/scripts/createSymlinks.sh
COPY pm_global.properties /src/test/resources/str_data/global.properties
