/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2012
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/

package com.ericsson.oss.services.pm.initiation.constants;

/**
 * The Pmic log commands enum.
 */
public enum PmicLogCommands {
    PMIC_POST_SUBSCRIPTION("PMIC.POST_SUBSCRIPTION"),
    PMIC_SUBSCRIPTION_ALREADY_EXISTS("PMIC.SUBSCRIPTION_ALREADY_EXISTS"),
    PMIC_PERSIST_SUBSCRIPTION("PMIC.PERSIST_SUBSCRIPTION"),
    PMIC_UPGRADE_NOTIFICATION("Upgrade notification"),
    PMIC_UNEXPECTED_UPGRADE_NOTIFICATION("Unexpected upgrade notification"),
    PMIC_UPDATE_SUBSCRIPTION_LIST("PMIC.UPDATE_SUBSCRIPTION_LIST"),
    PMIC_NO_SUBSCRIPTION_IN_THE_XML("PMIC.NO_SUBSCRIPTION_IN_THE_XML"),
    PMIC_PUT_SUBSCRIPTION("PMIC.PUT_SUBSCRIPTION"),
    PMIC_DELETE_ALL_NODES("PMIC.DELETE_ALL_NODES"),
    PMIC_CREATING_NODES_WITH_MIM_VERSION("PMIC.CREATING_NODES_WITH_MIM_VERSION"),
    PMIC_NODES_LIST("PMIC.NODES_LIST"),
    PMIC_CREATING_FILE_COLLECTION_JOB_LIST("PMIC.CREATING_FILE_COLLECTION_JOB_LIST"),
    PMIC_FILE_COLLECTION_JOB_LIST("PMIC.PMIC_FILE_COLLECTION_JOB_LIST"),
    PMIC_NODES_SEARCH("PMIC.NODES_SEARCH"),
    PMIC_SENDING_FILE_COLLECTION_JOBS("PMIC.SENDING_FILE_COLLECTION_JOBS"),
    PMIC_UPDATE_SUBSCRIPTION_IN_DPS_STARTED("PMIC.UPDATE_SUBSCRIPTION_IN_DPS_STARTED"),
    PMIC_GETTING_NODES_FROM_MO("PMIC.GETTING_NODES_FROM_MO"),
    PMIC_CONVERTING_NODES_FROM_MO("PMIC.CONVERTING_NODES_FROM_MO"),
    PMIC_PERSISTENCE_SUBSCRIPTION_FAILURE("PMIC.PERSISTENCE_SUBSCRIPTION_FAILURE_"),
    PMIC_ACTIVE_SUB_CANT_DELETE("PMIC.ACTIVE_SUB_CANT_DELETE_"),
    PMIC_SUBSCRIPTION_PATTERN_DOES_NOT_EXIST("PMIC.SUBSCRIPTION_PATTERN_DOES_NOT_EXIST_"),
    PMIC_DELETE_SUBSCRIPTION("PMIC.DELETE_SUBSCRIPTION"),
    PMIC_DELETE_INVALID_INPUT("PMIC.DELETE_INVALID_INPUT"),
    PMIC_DELETE_INTERNAL_SERVER_ERROR("PMIC.DELETE_INTERNAL_SERVER_ERROR"),
    PMIC_UPDATE_SUBSCRIPTION_ATTRIBUTES("PMIC.UPDATE_SUBSCRIPTION_ATTRIBUTES"),
    DPS_CREATE_NOTIFICATION("DPS CREATE NOTIFICATION"),
    DPS_DELETE_NOTIFICATION("DPS DELETE NOTIFICATION"),
    PMIC_PERSIST_SUBSCRIPTION_LIST("PMIC.PERSIST_SUBSCRIPTION_LIST"),
    PMIC_ACTIVATE_SUBSCRIPTION("PMIC.ACTIVATE_SUBSCRIPTION"),
    PMIC_DEACTIVATE_SUBSCRIPTION("PMIC.DEACTIVATE_SUBSCRIPTION"),
    PMIC_UPDATE_SUBSCRIPTION("PMIC.UPDATE_SUBSCRIPTION"),
    PMIC_UPDATING_SUBSCRIPTION("PMIC.UPDATING_SUBSCRIPTION"),
    PMIC_DELETING_SUBSCRIPTION("PMIC.DELETING_SUBSCRIPTION"),
    PMIC_SUBSCRIPTION_ID("PMIC.SUBSCRIPTION_ID "),
    PMIC_SUBSCRIPTION_DOES_NOT_EXISTS("SUBSCRIPTION_DOES_NOT_EXISTS_"),
    PMIC_DELETE_NODES("PMIC.DELETE_NODES"),
    PMIC_FETCH_SUBSCRIPTION("PMIC.FETCH_SUBSCRIPTION"),
    PMIC_CREATE_NODES_WITH_MIM_VERSION("PMIC.CREATE_NODES_WITH_MIM_VERSION"),
    PMIC_NODE_NOT_FOUND("NODE_NOT_FOUND"),
    PMIC_DPS_DELETE_SUBSCRIPTION("PMIC.DPS_DELETE_SUBSCRIPTION"),
    PMIC_DPS_PERSIST_SUBSCRIPTION("PMIC.DPS_PERSIST_SUBSCRIPTION"),
    PMIC_DPS_UPDATE_SUBSCRIPTION("PMIC.DPS_UPDATE_SUBSCRIPTION"),
    PMIC_DPS_PERSIST_UPDATE_SUBSCRIPTION("PMIC.PERSIST_SUBSCRIPTION/PMIC.UPDATE_SUBSCRIPTION"),
    PMIC_ERROR_CONVERTING_NODE_OBJECT_FROM_MO("ERROR_CONVERTING_NODE_OBJECT_FROM_MO"),
    PMIC_STARTUP("ERROR_CONVERTING_NODE_OBJECT_FROM_MO"),
    PMIC_FILE_COLLECTION_STATISTICS("PMIC_FILE_COLLECTION_STATISTICS"),
    PMIC_PRE_DESTROY("PMIC_PRE_DESTROY"),
    PMIC_INSTRUMENTATION_INTERCEPTOR("PMIC_INSTRUMENTATION_INTERCEPTOR"),
    PMIC_SUBSCRIPTION_AUDIT("PMIC_SUBSCRIPTION_AUDIT");

    private final String description;

    /**
     * @param description
     *         - log command description
     */
    PmicLogCommands(final String description) {
        this.description = description;
    }

    /**
     * Gets description.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }
}
