description: Invalid request
body:
  application/json:
    example: |
      {
        "code": "BAD_REQUEST",
        "error": "SubscriptionName has invalid characters",
        "parameters": []
      }
