description: User has no right perform this action
body:
  application/json:
    example: |
      {
        "code": "FORBIDDEN",
        "error": "Your Role does not allow you to perform this action.Contact System Administrator to change your access rights.",
        "parameters": []
      }
