description: Internal server error
body:
  application/json:
    example: |
      {
        "code": "INTERNAL_SERVER_ERROR",
        "error": "Service temporary unavailable",
        "parameters": []
      }
